"use client";

import { FormEvent, useMemo, useState } from "react";
import styles from "./page.module.css";

type PresignResponse = {
  success: boolean;
  data: {
    uploadUrl: string;
    objectKey: string;
    fileUrl: string;
    bucket: string;
    region: string;
    expiresInSeconds: number;
    method: "PUT";
    headers: {
      "Content-Type": string;
    };
  };
};

const apiBaseUrl = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:5001/api/v1";

export default function UploadsPage() {
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [folder, setFolder] = useState("assets");
  const [status, setStatus] = useState("Ready for a test upload.");
  const [isUploading, setIsUploading] = useState(false);
  const [objectKey, setObjectKey] = useState("");
  const [fileUrl, setFileUrl] = useState("");
  const [error, setError] = useState("");

  const canUpload = useMemo(
    () => Boolean(selectedFile && folder.trim() && !isUploading),
    [folder, isUploading, selectedFile]
  );

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    setError("");
    setObjectKey("");
    setFileUrl("");

    if (!selectedFile) {
      setError("Choose a file before requesting a pre-signed URL.");
      return;
    }

    setIsUploading(true);
    setStatus("Requesting a pre-signed URL...");

    try {
      const presignResponse = await fetch(`${apiBaseUrl}/media/uploads/presign`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          originalFileName: selectedFile.name,
          mimeType: selectedFile.type || "application/octet-stream",
          folder,
        }),
      });

      if (!presignResponse.ok) {
        const errorPayload = await presignResponse.json().catch(() => null);
        throw new Error(
          errorPayload?.error?.message || "Failed to generate a pre-signed upload URL."
        );
      }

      const payload = (await presignResponse.json()) as PresignResponse;

      setStatus("Uploading the file directly to S3...");

      const uploadResponse = await fetch(payload.data.uploadUrl, {
        method: "PUT",
        headers: {
          "Content-Type": selectedFile.type || payload.data.headers["Content-Type"],
        },
        body: selectedFile,
      });

      if (!uploadResponse.ok) {
        throw new Error(`S3 upload failed with status ${uploadResponse.status}.`);
      }

      setObjectKey(payload.data.objectKey);
      setFileUrl(payload.data.fileUrl);
      setStatus("Upload completed successfully.");
    } catch (uploadError) {
      if (uploadError instanceof TypeError) {
        setError(
          "The browser could not PUT the file to S3. Check the bucket CORS policy for localhost:3000 and allow PUT requests with the Content-Type header."
        );
      } else {
        setError(uploadError instanceof Error ? uploadError.message : "Upload failed.");
      }
      setStatus("Upload failed.");
    } finally {
      setIsUploading(false);
    }
  }

  return (
    <main className={styles.page}>
      <section className={styles.hero}>
        <p className={styles.kicker}>Development only</p>
        <h1>Media Uploads</h1>
        <p className={styles.description}>
          Test the browser-to-S3 flow with pre-signed PUT URLs generated by the backend.
        </p>
      </section>

      <section className={styles.grid}>
        <form className={styles.panel} onSubmit={handleSubmit}>
          <label className={styles.field}>
            <span>File</span>
            <input
              type="file"
              onChange={(event) => setSelectedFile(event.target.files?.[0] ?? null)}
            />
          </label>

          <label className={styles.field}>
            <span>Folder / category</span>
            <input
              type="text"
              value={folder}
              onChange={(event) => setFolder(event.target.value)}
              placeholder="assets"
            />
          </label>

          <button type="submit" disabled={!canUpload}>
            {isUploading ? "Uploading..." : "Request URL and Upload"}
          </button>

          <div className={styles.meta}>
            <p>
              <strong>API:</strong> {apiBaseUrl}
            </p>
            <p>
              <strong>Selected file:</strong> {selectedFile ? selectedFile.name : "None"}
            </p>
            <p>
              <strong>Browser PUT:</strong> S3 bucket CORS must allow your frontend origin.
            </p>
          </div>
        </form>

        <aside className={styles.panel}>
          <div className={styles.statusBlock}>
            <span className={styles.statusLabel}>Status</span>
            <p>{status}</p>
          </div>

          {error ? <p className={styles.error}>{error}</p> : null}

          <div className={styles.resultBlock}>
            <span className={styles.statusLabel}>Object key</span>
            <p>{objectKey || "Waiting for a successful upload."}</p>
          </div>

          <div className={styles.resultBlock}>
            <span className={styles.statusLabel}>File URL</span>
            {fileUrl ? (
              <a href={fileUrl} target="_blank" rel="noreferrer">
                {fileUrl}
              </a>
            ) : (
              <p>Waiting for a successful upload.</p>
            )}
          </div>
        </aside>
      </section>
    </main>
  );
}